<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AppProject.Core.Contracs\AppProject.Core.Contracs.csproj" />
    <ProjectReference Include="..\AppProject.Core.Controllers.General\AppProject.Core.Controllers.General.csproj" />
    <ProjectReference Include="..\AppProject.Core.Infra.AI\AppProject.Core.Infra.AI.csproj" />
    <ProjectReference Include="..\AppProject.Core.Infra.Database\AppProject.Core.Infra.Database.csproj" />
    <ProjectReference Include="..\AppProject.Core.Infra.Email\AppProject.Core.Infra.Email.csproj" />
    <ProjectReference Include="..\AppProject.Core.Infra.Jobs\AppProject.Core.Infra.Jobs.csproj" />
    <ProjectReference Include="..\AppProject.Core.Serv.General\AppProject.Core.Serv.General.csproj" />
    <ProjectReference Include="..\AppProject.Core.Services\AppProject.Core.Services.csproj" />
    <ProjectReference Include="..\AppProject.Resources\AppProject.Resources.csproj" />
    <ProjectReference Include="..\AppProject.Utils\AppProject.Utils.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Bootstraps\" />
    <Folder Include="Middlewares\" />
  </ItemGroup>

</Project>
